apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: myquota-e4c1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: myquota-e4c1
    app.kubernetes.io/part-of: myquota
  name: myquota-e4c1
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: go-app
    app.kubernetes.io/instance: myquota-e4c1
status:
  loadBalancer: {}
